/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface Employee {
  id: number;
  nama: string;
  nip: string;
  gender: 'L' | 'P';
  tempatLahir: string;
  tanggalLahir: string; // DD/MM/YYYY
  usiaTahun: number;
  usiaBulan: number;
  tmtCpns: string; // DD/MM/YYYY
  golongan: string; // e.g. "IV/d", "IV/c", "III/c"
  pangkat: string; // e.g. "Pembina Utama Madya", "Pembina"
  jabatanTerakhir: string;
  rumpunJabatan: string; // "Jabatan Fungsional Tertentu", "Jabatan Struktural", "Jabatan Fungsional Umum/ Pelaksana"
  pendidikanTerakhir: string;
  tingkatPendidikanTerakhir: string; // "S2", "S1", "DIII", "DIV Profesi", "SMA/SLTA", "S2 Profesi"
  unitRuangan: string;
  bidang: string; // "Bidang Pelayanan Medik", "Bidang Pelayanan Keperawatan", "Bidang Pelayanan Penunjang", "Bagian Perencanaan", "Bagian Sekretariat", etc.
  statusKepegawaian: 'Aktif' | 'Cuti' | 'Tugas Belajar' | 'Tidak Aktif Sementara';
  keterangan: string;
}

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 1,
    nama: "dr. Ni Made Suratnasih, Sp.M.",
    nip: "196206191988032007",
    gender: "P",
    tempatLahir: "Gianyar",
    tanggalLahir: "19/06/1962",
    usiaTahun: 63,
    usiaBulan: 11,
    tmtCpns: "01/03/1988",
    golongan: "IV/d",
    pangkat: "Pembina Utama Madya",
    jabatanTerakhir: "Dokter Ahli Utama",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Dokter Spesialis Mata",
    tingkatPendidikanTerakhir: "S2",
    unitRuangan: "Klinik Mata",
    bidang: "Bidang Pelayanan Medik",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 2,
    nama: "dr. Magdalena Kabiu, Sp.THT.",
    nip: "196211251989032007",
    gender: "P",
    tempatLahir: "Palopo",
    tanggalLahir: "25/11/1962",
    usiaTahun: 63,
    usiaBulan: 6,
    tmtCpns: "01/03/1989",
    golongan: "IV/d",
    pangkat: "Pembina Utama Madya",
    jabatanTerakhir: "Dokter Ahli Utama",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Dokter Spesialis T.H.T",
    tingkatPendidikanTerakhir: "S2",
    unitRuangan: "Klinik THT",
    bidang: "Bidang Pelayanan Medik",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 3,
    nama: "dr. H. Refinaldi, Sp.OG.",
    nip: "196305141990011001",
    gender: "L",
    tempatLahir: "Lubuk Sikaping",
    tanggalLahir: "14/05/1963",
    usiaTahun: 63,
    usiaBulan: 1,
    tmtCpns: "01/01/1990",
    golongan: "IV/d",
    pangkat: "Pembina Utama Madya",
    jabatanTerakhir: "Dokter Ahli Utama",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Dokter Spesialis Obgyn",
    tingkatPendidikanTerakhir: "S2",
    unitRuangan: "Klinik Kandungan",
    bidang: "Bidang Pelayanan Medik",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 4,
    nama: "dr. Rustan Samsuddin, M.M.",
    nip: "196711012001121003",
    gender: "L",
    tempatLahir: "Barru",
    tanggalLahir: "01/11/1967",
    usiaTahun: 58,
    usiaBulan: 7,
    tmtCpns: "01/12/2001",
    golongan: "IV/c",
    pangkat: "Pembina Utama Muda",
    jabatanTerakhir: "Direktur",
    rumpunJabatan: "Jabatan Struktural",
    pendidikanTerakhir: "Magister Manajemen",
    tingkatPendidikanTerakhir: "S2",
    unitRuangan: "Direktur",
    bidang: "Direktur",
    statusKepegawaian: "Aktif",
    keterangan: ""
  },
  {
    id: 5,
    nama: "Ns. Hadransyah, S.ST.",
    nip: "197101011991031010",
    gender: "L",
    tempatLahir: "Tanah Grogot",
    tanggalLahir: "01/01/1971",
    usiaTahun: 55,
    usiaBulan: 5,
    tmtCpns: "01/03/1991",
    golongan: "IV/c",
    pangkat: "Pembina Utama Muda",
    jabatanTerakhir: "Perawat Ahli Madya",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Keperawatan Ners",
    tingkatPendidikanTerakhir: "DIV Profesi",
    unitRuangan: "Komite Pelayanan Keperawatan",
    bidang: "Bidang Pelayanan Keperawatan",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 6,
    nama: "Usman, S.E., M.HP.",
    nip: "196805011992031013",
    gender: "L",
    tempatLahir: "Bulungan",
    tanggalLahir: "01/05/1968",
    usiaTahun: 58,
    usiaBulan: 1,
    tmtCpns: "01/03/1992",
    golongan: "IV/b",
    pangkat: "Pembina Tk.I",
    jabatanTerakhir: "Kabid. Perencanaan",
    rumpunJabatan: "Jabatan Struktural",
    pendidikanTerakhir: "Magister Hukum dan Pembangunan",
    tingkatPendidikanTerakhir: "S2",
    unitRuangan: "Kepala Bidang Perencanaan",
    bidang: "Bagian Perencanaan",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 7,
    nama: "Ns. Triana Kusumaningsih, S.Kep.",
    nip: "198006112009032002",
    gender: "P",
    tempatLahir: "Madiun",
    tanggalLahir: "11/06/1980",
    usiaTahun: 46,
    usiaBulan: 0,
    tmtCpns: "01/03/2009",
    golongan: "IV/a",
    pangkat: "Pembina",
    jabatanTerakhir: "Kabid. Pelayanan Keperawatan",
    rumpunJabatan: "Jabatan Struktural",
    pendidikanTerakhir: "Keperawatan Ners",
    tingkatPendidikanTerakhir: "S1 Profesi",
    unitRuangan: "Kepala Bidang Pelayanan Keperawatan",
    bidang: "Bidang Pelayanan Keperawatan",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 8,
    nama: "dr. Wayan Sukadana",
    nip: "196608061999031004",
    gender: "L",
    tempatLahir: "Gianyar",
    tanggalLahir: "06/08/1966",
    usiaTahun: 59,
    usiaBulan: 10,
    tmtCpns: "01/03/1999",
    golongan: "IV/c",
    pangkat: "Pembina Utama Muda",
    jabatanTerakhir: "Dokter Ahli Madya",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Dokter Umum",
    tingkatPendidikanTerakhir: "S1 Profesi",
    unitRuangan: "Case Manager",
    bidang: "Bidang Pelayanan Medik",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 9,
    nama: "Ns. Abdul Karim, S.ST.",
    nip: "197009061991031012",
    gender: "L",
    tempatLahir: "Long Kali",
    tanggalLahir: "06/09/1970",
    usiaTahun: 55,
    usiaBulan: 9,
    tmtCpns: "01/03/1991",
    golongan: "IV/c",
    pangkat: "Pembina Utama Muda",
    jabatanTerakhir: "Perawat Ahli Madya",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Keperawatan Ners",
    tingkatPendidikanTerakhir: "DIV Profesi",
    unitRuangan: "Instalasi Gawat Darurat (IGD)",
    bidang: "Bidang Pelayanan Keperawatan",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 10,
    nama: "Ns. Abdul Kadir, S.ST.",
    nip: "196802051991031009",
    gender: "L",
    tempatLahir: "Balikpapan",
    tanggalLahir: "05/02/1968",
    usiaTahun: 58,
    usiaBulan: 4,
    tmtCpns: "01/03/1991",
    golongan: "IV/c",
    pangkat: "Pembina Utama Muda",
    jabatanTerakhir: "Perawat Ahli Madya",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Keperawatan Ners",
    tingkatPendidikanTerakhir: "DIV Profesi",
    unitRuangan: "Case Manager",
    bidang: "Bidang Pelayanan Keperawatan",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 11,
    nama: "Ns. Petrus Senin, S.ST.",
    nip: "196704121989031013",
    gender: "L",
    tempatLahir: "Toraja",
    tanggalLahir: "12/04/1967",
    usiaTahun: 59,
    usiaBulan: 2,
    tmtCpns: "01/03/1989",
    golongan: "IV/c",
    pangkat: "Pembina Utama Muda",
    jabatanTerakhir: "Perawat Ahli Madya",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Keperawatan Ners",
    tingkatPendidikanTerakhir: "DIV Profesi",
    unitRuangan: "Poliklinik Rawat Jalan",
    bidang: "Bidang Pelayanan Keperawatan",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 12,
    nama: "dr. Ario Gatot Kertarto",
    nip: "196901271999031002",
    gender: "L",
    tempatLahir: "Jakarta",
    tanggalLahir: "27/01/1969",
    usiaTahun: 57,
    usiaBulan: 4,
    tmtCpns: "01/03/1999",
    golongan: "IV/c",
    pangkat: "Pembina Utama Muda",
    jabatanTerakhir: "Dokter Ahli Madya",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Dokter Umum",
    tingkatPendidikanTerakhir: "S1 Profesi",
    unitRuangan: "Case Manager",
    bidang: "Bidang Pelayanan Medik",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 13,
    nama: "Yurisa Kinanti, S.Si., Apt.",
    nip: "198408172009032012",
    gender: "P",
    tempatLahir: "Tarakan",
    tanggalLahir: "17/08/1984",
    usiaTahun: 41,
    usiaBulan: 10,
    tmtCpns: "01/03/2009",
    golongan: "IV/c",
    pangkat: "Pembina Utama Muda",
    jabatanTerakhir: "Apoteker Ahli Madya",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Apoteker",
    tingkatPendidikanTerakhir: "S1 Profesi",
    unitRuangan: "Apotik Rawat Inap",
    bidang: "Bidang Pelayanan Penunjang",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 14,
    nama: "dr. Amir Saudin Sibarani, Sp.BA.",
    nip: "197704122006041019",
    gender: "L",
    tempatLahir: "Medan",
    tanggalLahir: "12/04/1977",
    usiaTahun: 49,
    usiaBulan: 2,
    tmtCpns: "01/04/2006",
    golongan: "IV/c",
    pangkat: "Pembina Utama Muda",
    jabatanTerakhir: "Dokter Ahli Madya",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Dokter Spesialis Bedah Anak",
    tingkatPendidikanTerakhir: "S2 Profesi",
    unitRuangan: "Klinik Bedah Anak",
    bidang: "Bidang Pelayanan Medik",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 15,
    nama: "dr. Dewi Mandang, Sp.OG.",
    nip: "197109162008032001",
    gender: "P",
    tempatLahir: "Tarakan",
    tanggalLahir: "16/09/1971",
    usiaTahun: 54,
    usiaBulan: 9,
    tmtCpns: "01/03/2008",
    golongan: "IV/c",
    pangkat: "Pembina Utama Muda",
    jabatanTerakhir: "Dokter Ahli Madya",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Dokter Spesialis Obgyn",
    tingkatPendidikanTerakhir: "S2 Profesi",
    unitRuangan: "Klinik Kandungan",
    bidang: "Bidang Pelayanan Medik",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 16,
    nama: "dr. Eny Margayati",
    nip: "198111212008032003",
    gender: "P",
    tempatLahir: "Nganjuk",
    tanggalLahir: "21/11/1981",
    usiaTahun: 44,
    usiaBulan: 6,
    tmtCpns: "01/03/2008",
    golongan: "IV/c",
    pangkat: "Pembina Utama Muda",
    jabatanTerakhir: "Dokter Ahli Madya",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Dokter Umum",
    tingkatPendidikanTerakhir: "S1 Profesi",
    unitRuangan: "Pelayanan Medis",
    bidang: "Bidang Pelayanan Medik",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 17,
    nama: "Sri Listyawati, S.Farm., Apt.",
    nip: "198304202009032004",
    gender: "P",
    tempatLahir: "Tarakan",
    tanggalLahir: "20/04/1983",
    usiaTahun: 43,
    usiaBulan: 1,
    tmtCpns: "01/03/2009",
    golongan: "IV/b",
    pangkat: "Pembina Tk.I",
    jabatanTerakhir: "Apoteker Ahli Madya",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Apoteker",
    tingkatPendidikanTerakhir: "S1 Profesi",
    unitRuangan: "Pengadaan Barang Unit",
    bidang: "Bidang Pelayanan Penunjang",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 18,
    nama: "dr. Karomah Sriwedari, Sp.PK",
    nip: "198005122008032002",
    gender: "P",
    tempatLahir: "Jember",
    tanggalLahir: "12/05/1980",
    usiaTahun: 46,
    usiaBulan: 1,
    tmtCpns: "01/03/2008",
    golongan: "IV/c",
    pangkat: "Pembina Utama Muda",
    jabatanTerakhir: "Dokter Ahli Madya",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Dokter Spesialis Patologi Klinik",
    tingkatPendidikanTerakhir: "S2 Profesi",
    unitRuangan: "Pelayanan Medis",
    bidang: "Bidang Pelayanan Medik",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 19,
    nama: "dr. Budy Azis B, Sp.PK., M.H.",
    nip: "197403302008031002",
    gender: "L",
    tempatLahir: "Ujung Pandang",
    tanggalLahir: "30/03/1974",
    usiaTahun: 52,
    usiaBulan: 2,
    tmtCpns: "01/03/2008",
    golongan: "IV/b",
    pangkat: "Pembina Tk.I",
    jabatanTerakhir: "Wakil Direktur Pelayanan",
    rumpunJabatan: "Jabatan Struktural",
    pendidikanTerakhir: "Dokter Spesialis Patologi Klinik",
    tingkatPendidikanTerakhir: "S2 Profesi",
    unitRuangan: "Wakil Direktur",
    bidang: "Wakil Direktur Pelayanan",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 20,
    nama: "dr. Made Widyarini",
    nip: "196808212002122003",
    gender: "P",
    tempatLahir: "Surabaya",
    tanggalLahir: "21/08/1968",
    usiaTahun: 57,
    usiaBulan: 9,
    tmtCpns: "01/12/2002",
    golongan: "IV/c",
    pangkat: "Pembina Utama Muda",
    jabatanTerakhir: "Dokter Ahli Madya",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Dokter Umum",
    tingkatPendidikanTerakhir: "S1 Profesi",
    unitRuangan: "Pelayanan Medis",
    bidang: "Bidang Pelayanan Medik",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 21,
    nama: "dr. Sigit Prastyanto, M.Sc., Sp.A.",
    nip: "196903072002121005",
    gender: "L",
    tempatLahir: "Lamongan",
    tanggalLahir: "07/03/1969",
    usiaTahun: 57,
    usiaBulan: 3,
    tmtCpns: "01/12/2002",
    golongan: "IV/c",
    pangkat: "Pembina Utama Muda",
    jabatanTerakhir: "Dokter Ahli Madya",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Dokter Spesialis Anak",
    tingkatPendidikanTerakhir: "S2 Profesi",
    unitRuangan: "Klinik Anak/ Tumbuh Kembang Anak",
    bidang: "Bidang Pelayanan Medik",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 22,
    nama: "Ns. Tugiono, S.Kep.",
    nip: "196909011991031006",
    gender: "L",
    tempatLahir: "Banjarmasin",
    tanggalLahir: "01/09/1969",
    usiaTahun: 56,
    usiaBulan: 9,
    tmtCpns: "01/03/1991",
    golongan: "IV/c",
    pangkat: "Pembina Utama Muda",
    jabatanTerakhir: "Perawat Ahli Madya",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Keperawatan Ners",
    tingkatPendidikanTerakhir: "S1 Profesi",
    unitRuangan: "Case Manager",
    bidang: "Bidang Pelayanan Keperawatan",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 23,
    nama: "Elyanto, S.E.",
    nip: "197310192000121001",
    gender: "L",
    tempatLahir: "Samarinda",
    tanggalLahir: "19/10/1973",
    usiaTahun: 52,
    usiaBulan: 7,
    tmtCpns: "01/12/2000",
    golongan: "IV/a",
    pangkat: "Pembina",
    jabatanTerakhir: "Kabag. Sekretariat",
    rumpunJabatan: "Jabatan Struktural",
    pendidikanTerakhir: "Sarjana Ekonomi",
    tingkatPendidikanTerakhir: "S1",
    unitRuangan: "Kepala Bagian Sekretariat",
    bidang: "Bagian Sekretariat",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 24,
    nama: "Ns. Bethy Mariana, S.Kep.",
    nip: "196705041989032010",
    gender: "P",
    tempatLahir: "Nunukan",
    tanggalLahir: "04/05/1967",
    usiaTahun: 59,
    usiaBulan: 1,
    tmtCpns: "01/03/1989",
    golongan: "IV/b",
    pangkat: "Pembina Tk.I",
    jabatanTerakhir: "Perawat Ahli Madya",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Keperawatan Ners",
    tingkatPendidikanTerakhir: "S1 Profesi",
    unitRuangan: "Komite Mutu",
    bidang: "Bidang Pelayanan Keperawatan",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 25,
    nama: "dr. Yufriadi Yunus, Sp.B.",
    nip: "197906182007011013",
    gender: "L",
    tempatLahir: "Ambon",
    tanggalLahir: "18/06/1979",
    usiaTahun: 46,
    usiaBulan: 11,
    tmtCpns: "01/01/2007",
    golongan: "IV/a",
    pangkat: "Pembina",
    jabatanTerakhir: "Dokter Ahli Muda",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Dokter Spesialis Bedah",
    tingkatPendidikanTerakhir: "S2 Profesi",
    unitRuangan: "Klinik Bedah Umum",
    bidang: "Bidang Pelayanan Medik",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 26,
    nama: "dr. Yuliani Bekti Susanti, Sp.PD.",
    nip: "197707312007012010",
    gender: "P",
    tempatLahir: "Bantul",
    tanggalLahir: "31/07/1977",
    usiaTahun: 48,
    usiaBulan: 10,
    tmtCpns: "01/01/2007",
    golongan: "IV/b",
    pangkat: "Pembina Tk.I",
    jabatanTerakhir: "Dokter Ahli Madya",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Dokter Spesialis Penyakit Dalam",
    tingkatPendidikanTerakhir: "S2 Profesi",
    unitRuangan: "Klinik Penyakit Dalam",
    bidang: "Bidang Pelayanan Medik",
    statusKepegawaian: "Cuti",
    keterangan: "Cuti Besar"
  },
  {
    id: 27,
    nama: "drg. Maria Montessory, Sp.BM.",
    nip: "198508302010012023",
    gender: "P",
    tempatLahir: "Banjarmasin",
    tanggalLahir: "30/08/1985",
    usiaTahun: 40,
    usiaBulan: 9,
    tmtCpns: "01/01/2010",
    golongan: "IV/a",
    pangkat: "Pembina",
    jabatanTerakhir: "Dokter Gigi Ahli Madya",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Dokter Gigi Spesialis Bedah Mulut dan Maksilofasial",
    tingkatPendidikanTerakhir: "S2 Profesi",
    unitRuangan: "Klinik Bedah Mulut dan Maksilofasial",
    bidang: "Bidang Pelayanan Medik",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 28,
    nama: "dr. Ronald Jan Palenteng, Sp.An-TI., FCTA.",
    nip: "198101202009031005",
    gender: "L",
    tempatLahir: "Manado",
    tanggalLahir: "20/01/1981",
    usiaTahun: 45,
    usiaBulan: 4,
    tmtCpns: "01/03/2009",
    golongan: "IV/a",
    pangkat: "Pembina",
    jabatanTerakhir: "Kabid. Pelayanan Medik",
    rumpunJabatan: "Jabatan Struktural",
    pendidikanTerakhir: "Dokter Spesialis Anestesiologi",
    tingkatPendidikanTerakhir: "S2 Profesi",
    unitRuangan: "Kepala Bidang Pelayanan Medik",
    bidang: "Bidang Pelayanan Medik",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 29,
    nama: "dr. Jerry Kurnia Wahyudi, Sp.K.F.R.",
    nip: "198001012009031006",
    gender: "L",
    tempatLahir: "Samarinda",
    tanggalLahir: "01/01/1980",
    usiaTahun: 46,
    usiaBulan: 5,
    tmtCpns: "01/03/2009",
    golongan: "IV/c",
    pangkat: "Pembina Utama Muda",
    jabatanTerakhir: "Dokter Ahli Madya",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Dokter Spesialis Ilmu Kedokteran Fisik dan Rehabilitasi",
    tingkatPendidikanTerakhir: "S2 Profesi",
    unitRuangan: "Rehab Medik",
    bidang: "Bidang Pelayanan Medik",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 30,
    nama: "dr. Andi Rizal, Sp.Rad.",
    nip: "197607202006041010",
    gender: "L",
    tempatLahir: "Sidrap",
    tanggalLahir: "20/07/1976",
    usiaTahun: 49,
    usiaBulan: 10,
    tmtCpns: "01/04/2006",
    golongan: "IV/a",
    pangkat: "Pembina",
    jabatanTerakhir: "Dokter Ahli Muda",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Dokter Spesialis Radiologi",
    tingkatPendidikanTerakhir: "S2 Profesi",
    unitRuangan: "Pelayanan Medis",
    bidang: "Bidang Pelayanan Medik",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 31,
    nama: "Yusran, S.T., M.T.",
    nip: "197409122005021001",
    gender: "L",
    tempatLahir: "Ujung Pandang",
    tanggalLahir: "12/09/1974",
    usiaTahun: 51,
    usiaBulan: 9,
    tmtCpns: "01/02/2005",
    golongan: "IV/b",
    pangkat: "Pembina Tk.I",
    jabatanTerakhir: "Wakil Direktur Umum",
    rumpunJabatan: "Jabatan Struktural",
    pendidikanTerakhir: "Magister Teknik Sipil",
    tingkatPendidikanTerakhir: "S2",
    unitRuangan: "Wakil Direktur",
    bidang: "Wakil Direktur Umum",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 32,
    nama: "Zakiyah Machluddin, SKM.",
    nip: "197706212003122006",
    gender: "P",
    tempatLahir: "Ujung Pandang",
    tanggalLahir: "21/06/1977",
    usiaTahun: 48,
    usiaBulan: 11,
    tmtCpns: "01/12/2003",
    golongan: "IV/a",
    pangkat: "Pembina",
    jabatanTerakhir: "Kabag. Organisasi Kepegawaian dan Diklit",
    rumpunJabatan: "Jabatan Struktural",
    pendidikanTerakhir: "Sarjana Kesehatan Masyarakat",
    tingkatPendidikanTerakhir: "S1",
    unitRuangan: "Kepala Bagian Organisasi Kepegawaian dan Diklit",
    bidang: "Bagian Organisasi Kepegawaian dan Diklit",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 33,
    nama: "Ns. Jurlina Birro, S.Kep., M.Kep.",
    nip: "198307062009032003",
    gender: "P",
    tempatLahir: "Rantetayo",
    tanggalLahir: "06/07/1983",
    usiaTahun: 42,
    usiaBulan: 11,
    tmtCpns: "01/03/2009",
    golongan: "IV/b",
    pangkat: "Pembina Tk.I",
    jabatanTerakhir: "Perawat Ahli Madya",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Magister Keperawatan",
    tingkatPendidikanTerakhir: "S2",
    unitRuangan: "PPI",
    bidang: "Bidang Pelayanan Keperawatan",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 34,
    nama: "dr. Rahmawati Nur Indah, Sp.KJ.",
    nip: "197811072011012001",
    gender: "P",
    tempatLahir: "Tarakan",
    tanggalLahir: "07/11/1978",
    usiaTahun: 47,
    usiaBulan: 7,
    tmtCpns: "01/01/2011",
    golongan: "IV/b",
    pangkat: "Pembina Tk.I",
    jabatanTerakhir: "Dokter Ahli Madya",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Dokter Spesialis Kedokteran Jiwa",
    tingkatPendidikanTerakhir: "S2 Profesi",
    unitRuangan: "Kini Klinik Jiwa",
    bidang: "Bidang Pelayanan Medik",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 35,
    nama: "dr. Morlim Limbong, Sp.J.P.",
    nip: "198309032009031004",
    gender: "L",
    tempatLahir: "Samarinda",
    tanggalLahir: "03/09/1983",
    usiaTahun: 42,
    usiaBulan: 9,
    tmtCpns: "01/03/2009",
    golongan: "IV/b",
    pangkat: "Pembina Tk.I",
    jabatanTerakhir: "Dokter Ahli Madya",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Dokter Spesialis Jantung dan Pembuluh Darah",
    tingkatPendidikanTerakhir: "S2 Profesi",
    unitRuangan: "Klinik Jantung",
    bidang: "Bidang Pelayanan Medik",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 36,
    nama: "dr. Dian Artanti, Sp.A.",
    nip: "198401212009032002",
    gender: "P",
    tempatLahir: "Samarinda",
    tanggalLahir: "21/01/1984",
    usiaTahun: 42,
    usiaBulan: 4,
    tmtCpns: "01/03/2009",
    golongan: "IV/b",
    pangkat: "Pembina Tk.I",
    jabatanTerakhir: "Dokter Ahli Madya",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Dokter Spesialis Anak",
    tingkatPendidikanTerakhir: "S2 Profesi",
    unitRuangan: "Klinik Anak/ Tumbuh Kembang Anak",
    bidang: "Bidang Pelayanan Medik",
    statusKepegawaian: "Tugas Belajar",
    keterangan: "Tugas Belajar"
  },
  {
    id: 37,
    nama: "Lidya Mildiana, S.Sos., M.PSDM",
    nip: "198405162011012001",
    gender: "P",
    tempatLahir: "Samarinda",
    tanggalLahir: "16/05/1984",
    usiaTahun: 42,
    usiaBulan: 1,
    tmtCpns: "01/01/2011",
    golongan: "III/c",
    pangkat: "Penata",
    jabatanTerakhir: "Analis Sumber Daya Manusia Aparatur Ahli Muda",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Magister Pengembangan Sumber Daya Manusia",
    tingkatPendidikanTerakhir: "S2",
    unitRuangan: "Sub Kepegawaian",
    bidang: "Bagian Kepegawaian dan Diklit",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 38,
    nama: "Sari, S.H",
    nip: "198612112010012001",
    gender: "P",
    tempatLahir: "Ujung Pandang",
    tanggalLahir: "11/12/1986",
    usiaTahun: 39,
    usiaBulan: 6,
    tmtCpns: "01/01/2010",
    golongan: "III/c",
    pangkat: "Penata",
    jabatanTerakhir: "Auditor Ahli Muda",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Sarjana Hukum",
    tingkatPendidikanTerakhir: "S1",
    unitRuangan: "Komite Satuan Pengawas Internal",
    bidang: "Pengawasan Internal",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 39,
    nama: "Irma Ulfa, S.Kom",
    nip: "198106242015032003",
    gender: "P",
    tempatLahir: "Tarakan",
    tanggalLahir: "24/06/1981",
    usiaTahun: 44,
    usiaBulan: 11,
    tmtCpns: "01/03/2015",
    golongan: "III/c",
    pangkat: "Penata",
    jabatanTerakhir: "Pranata Komputer Ahli Pertama",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Sarjana Komputer",
    tingkatPendidikanTerakhir: "S1",
    unitRuangan: "SIMRS",
    bidang: "Bagian Sekretariat",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 40,
    nama: "Apt. Novia Widyani, S.Si",
    nip: "199504252019032008",
    gender: "P",
    tempatLahir: "Tana Toraja",
    tanggalLahir: "25/04/1995",
    usiaTahun: 31,
    usiaBulan: 1,
    tmtCpns: "01/03/2019",
    golongan: "III/c",
    pangkat: "Penata",
    jabatanTerakhir: "Apoteker Ahli Muda",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Apoteker",
    tingkatPendidikanTerakhir: "S1 Profesi",
    unitRuangan: "Depo Rawat Jalan",
    bidang: "Bidang Pelayanan Penunjang",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 41,
    nama: "drg. Agustini Ria Ningsih",
    nip: "199308092022032003",
    gender: "P",
    tempatLahir: "Tarakan",
    tanggalLahir: "09/08/1993",
    usiaTahun: 32,
    usiaBulan: 10,
    tmtCpns: "01/03/2022",
    golongan: "III/b",
    pangkat: "Penata Muda Tk.I",
    jabatanTerakhir: "Dokter Gigi Ahli Muda",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Dokter Gigi",
    tingkatPendidikanTerakhir: "S1",
    unitRuangan: "Klinik Gigi dan Mulut",
    bidang: "Bidang Pelayanan Medik",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 42,
    nama: "Ns. Renudin, S.Kep.",
    nip: "197512232009031001",
    gender: "L",
    tempatLahir: "Mandomai",
    tanggalLahir: "23/12/1975",
    usiaTahun: 50,
    usiaBulan: 5,
    tmtCpns: "01/03/2009",
    golongan: "IV/b",
    pangkat: "Pembina Tk.I",
    jabatanTerakhir: "Perawat Ahli Madya",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Keperawatan Ners",
    tingkatPendidikanTerakhir: "S1 Profesi",
    unitRuangan: "Komite Pelayanan Keperawatan",
    bidang: "Bidang Pelayanan Keperawatan",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 43,
    nama: "Ns. Basuki Rahmat, S.ST.",
    nip: "197011211991031005",
    gender: "L",
    tempatLahir: "Balikpapan",
    tanggalLahir: "21/11/1970",
    usiaTahun: 55,
    usiaBulan: 6,
    tmtCpns: "01/03/1991",
    golongan: "IV/b",
    pangkat: "Pembina Tk.I",
    jabatanTerakhir: "Perawat Ahli Madya",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Keperawatan Ners",
    tingkatPendidikanTerakhir: "S1 Profesi",
    unitRuangan: "Case Manager",
    bidang: "Bidang Pelayanan Keperawatan",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 44,
    nama: "Budi Susanto, S.E",
    nip: "197402132008011012",
    gender: "L",
    tempatLahir: "Bulungan",
    tanggalLahir: "13/02/1974",
    usiaTahun: 52,
    usiaBulan: 4,
    tmtCpns: "01/01/2008",
    golongan: "III/d",
    pangkat: "Penata Tk.I",
    jabatanTerakhir: "Analis Kebijakan Ahli Muda",
    rumpunJabatan: "Jabatan Fungsional Tertentu",
    pendidikanTerakhir: "Sarjana Ekonomi",
    tingkatPendidikanTerakhir: "S1",
    unitRuangan: "Bidang Pengelolaan Pendapatan",
    bidang: "Bidang Pengelolaan Pendapatan",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  },
  {
    id: 45,
    nama: "Ns. Jumiarti",
    nip: "197606182007012021",
    gender: "P",
    tempatLahir: "Nunukan",
    tanggalLahir: "18/06/1976",
    usiaTahun: 49,
    usiaBulan: 11,
    tmtCpns: "01/01/2007",
    golongan: "III/b",
    pangkat: "Penata Muda Tk.I",
    jabatanTerakhir: "Pengadministrasi Perkantoran",
    rumpunJabatan: "Jabatan Fungsional Umum/ Pelaksana",
    pendidikanTerakhir: "SLTA/Sederajat",
    tingkatPendidikanTerakhir: "SMA/SLTA",
    unitRuangan: "Bougenvile",
    bidang: "Bidang Pelayanan Keperawatan",
    statusKepegawaian: "Aktif",
    keterangan: "-"
  }
];
